# Use a Node base image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /client

# Copy package.json and package-lock.json
COPY client/package*.json ./

# Install project dependencies
RUN npm install

# Copy the client directory contents into the container at /client
COPY client/ .

ARG BUILD_ENV

# Development build

FROM base as development

ENV BUILD_ENV=development

CMD ["npm", "run", "dev"]

## Production build

FROM base as production

ENV BUILD_ENV=production

# Build the app
RUN npm run build

# Install serve to serve the static files
RUN npm install -g serve

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Run the app
CMD ["serve", "-s", "build"]

# Final stage: Select the build environment based on the BUILD_ENV argument
FROM ${BUILD_ENV} as final