name: "Bump Version"

description: "Bump the package version"

inputs:
  SEMVER_LEVEL:
    description: One of {patch, minor, major}
    required: false
    default: patch

runs:
  using: "composite"
  
  steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up pandoc
      uses: r-lib/actions/setup-pandoc@v2
      
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::glue, local::.
        needs: glue

    - name: Bump R package version
      run: |
        Rscript scripts/src/bump_version.R ${{ inputs.SEMVER_LEVEL }}
      shell: bash
