name: "Bump Version"

description: "Bump the package version"

inputs:
  SEMVER_LEVEL:
    description: One of {patch, minor, major}
    required: false
    default: patch

outputs:
  NEW_VERSION:
    description: The new version string
    value: ${{ steps.bumpVersion.outputs.NEW_VERSION }}

runs:
  using: "composite"
  
  steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        ref: release

    - name: Set up pandoc
      uses: r-lib/actions/setup-pandoc@v2
      
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::glue, local::.
        needs: glue

    - name: Bump the package version
      id: bumpVersion
      run: |
        Rscript ./.github/actions/composite/bumpVersion/bump_version.R ${{ inputs.SEMVER_LEVEL }}
      shell: bash
