name: "Bump Version"

description: "Bump the package version"

inputs:
  SEMVER_LEVEL:
    description: One of {patch, minor, major}
    required: false
    default: patch
  ARTMA_BOT_COMMIT_TOKEN:
    required: true
    description: 'Personal access token for ArtmaBot'
  LARGE_SECRET_PASSPHRASE:
    required: true
    description: 'GPG passphrase for committing as ArtmaBot'

outputs:
  NEW_VERSION:
    description: The new version string
    value: ${{ steps.bumpVersion.outputs.NEW_VERSION }}

runs:
  using: "composite"
  
  steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up pandoc
      uses: r-lib/actions/setup-pandoc@v2
      
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::glue, local::.
        needs: glue

    - name: Setup git for ArtmaBot
      uses: ./.github/actions/composite/setupGitForArtmaBot
      with:
        GPG_PASSPHRASE: ${{ inputs.LARGE_SECRET_PASSPHRASE }}

    - name: Bump the package version
      id: bumpVersion
      run: |
        NEW_VERSION=$(Rscript ./scripts/R/bump_version.R ${{ inputs.SEMVER_LEVEL }})
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT
      shell: bash

    - name: Commit the changes
      shell: bash
      run: |
        git add ./DESCRIPTION ./**/options_template.yaml
        git commit -m "chore: release v${{ steps.bumpVersion.outputs.NEW_VERSION }}"

    - name: Push the changes
      shell: bash
      run: |
        git remote set-url origin git@github.com:${{ github.repository }}.git
        git pull --rebase origin master
        git push origin master


