import { SessionProvider } from "next-auth/react"
import type { Metadata } from "next"
import { Session } from "next-auth"
// import { ThemeProvider } from "@/context/ThemeContext"
import { Providers } from "@/context/providers"
import Navbar from "@/components/Navbar"
import MyProfilePic from "@/components/MyProfilePic"
import Footer from "@/components/footer"

// Include shared components, SEO components, and global providers here

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode
  session: Session
}) {
  return (
    // <html lang="en" suppressHydrationWarning> {/* className={"something"}*/}
    //   <body className="bg-gray-50">
        <Providers session={session}> {/* ideally remove the session from here */}
          <Navbar />
          <main className="container mx-auto px-4">{children}</main>
          <Footer />
        </Providers>
    //   </body>
    // </html>
  )
}
