import { SessionProvider } from "next-auth/react"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Session } from "next-auth"

// Include shared components, SEO components, and global providers here

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode
  session: Session
}) {
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </SessionProvider>
  )
}
