import { SessionProvider } from "next-auth/react"
import type { Metadata } from "next"
import { Session } from "next-auth"
import { ThemeProvider } from "@/context/ThemeContext"

// Include shared components, SEO components, and global providers here

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode
  session: Session
}) {
  return (
    <ThemeProvider>
      <SessionProvider session={session}>
        {children}
      </SessionProvider>
    </ThemeProvider>
  )
}
