#! /usr/bin/env Rscript

# Get the release notes for a given tag - used to create the release notes for a new release

#' Slice one version's section out of the lines of NEWS.md.
#'
#' NEWS.md is generated by git-chglog, so every version starts with an
#' `<a name="vX.Y.Z"></a>` anchor, followed by the compare-link heading and the
#' release date. The body is everything between the date and the next anchor.
#'
#' @param lines *[character]* The lines of NEWS.md.
#' @param tag *[character]* Version tag to extract, e.g. `"v0.4.0"`.
#' @return *[character]* The section body, without the heading, the date, or
#'   surrounding blank lines.
extract_release_notes <- function(lines, tag) {
  anchor <- sprintf("<a name=\"%s\"></a>", tag)
  anchor_line <- which(trimws(lines) == anchor)
  if (length(anchor_line) == 0) {
    stop(sprintf("Could not find anchor tag '%s' in NEWS.md", anchor))
  }
  anchor_line <- anchor_line[[1]]

  later_anchors <- grep("^\\s*<a name=", lines)
  later_anchors <- later_anchors[later_anchors > anchor_line]
  end <- if (length(later_anchors) > 0) later_anchors[[1]] - 1L else length(lines)

  body <- if (end > anchor_line) lines[(anchor_line + 1L):end] else character(0)

  # Drop the compare-link heading, the release date, and any blank lines that
  # precede the first entry.
  is_preamble <- grepl("^\\s*(##\\s|>\\s|$)", body)
  first_entry <- which(!is_preamble)
  body <- if (length(first_entry) > 0) body[min(first_entry):length(body)] else character(0)

  # Drop trailing blank lines.
  last_entry <- which(nzchar(trimws(body)))
  body <- if (length(last_entry) > 0) body[1:max(last_entry)] else character(0)

  # A section holding nothing but group headings means git-chglog matched no
  # commits. Fail loudly rather than publishing an empty release body.
  if (!any(grepl("^\\s*[^#[:space:]]", body))) {
    stop(sprintf(
      paste0(
        "No release notes found for '%s' in NEWS.md. ",
        "git-chglog matched no commits for this version - check that the ",
        "checkout has full history (fetch-depth: 0) and that the header ",
        "pattern in .chglog/config.yml still matches the commit messages."
      ),
      tag
    ))
  }

  body
}

# Only read NEWS.md and write release-notes.md when run as a script
# (`Rscript`). testthat sets TESTTHAT=true for every worker, so tests that
# source this file to call extract_release_notes() directly do not trigger a
# write.
if (!identical(Sys.getenv("TESTTHAT"), "true")) {
  option_list <- list(
    optparse::make_option(c("--new-version"),
      type = "character",
      default = "Unknown",
      help = "New version to get release notes for [default = %default]",
      dest = "new_version"
    )
  )

  opt_parser <- optparse::OptionParser(option_list = option_list)
  opts <- optparse::parse_args(opt_parser)

  writeLines(
    extract_release_notes(readLines("NEWS.md", warn = FALSE), paste0("v", opts$new_version)),
    "release-notes.md"
  )
}
