# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples

name: Lint Check

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - master
    types: [opened]

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3.2"
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::lintr, local::.
          needs: lint

      - name: Debug R session
        run: |
          sessionInfo()
          installed.packages()[, c("Package", "Version")]
        shell: Rscript {0}

      - name: Lint
        run: lintr::lint_package()
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true
