# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples

name: Lint Check

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::lintr, local::.
          needs: lint

      # - name: Load the package and setup the runtime environment
      #   run: |
      #   shell: Rscript {0}
        
      - name: Lint
        run: |
          devtools::load_all()
          artma::static_setup()
          lintr::lint_package()
        shell: Rscript {0}

      - name: Print error trace
        if: failure()
        run: |
          cli::cli_inform("Linting failed. Printing error trace...")
          rlang::last_trace()
        shell: Rscript {0}
          

