name: Submit to CRAN

on:
  release:
    types: [published]

jobs:
  validateActor:
    runs-on: ubuntu-latest
    outputs:
      CAN_SUBMIT_TO_CRAN: ${{ contains(fromJSON('["admin"]'), steps.getUserPermissions.outputs.PERMISSION) }}
    steps:
      - name: Get user permissions
        id: getUserPermissions
        run: echo "PERMISSION=$(gh api /repos/${{ github.repository }}/collaborators/${{ github.actor }}/permission | jq -r '.permission')" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}

  submitToCran:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # Checkout to the tag that was used for the release
          ref: ${{ github.event.release.tag_name }}

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::curl, any::httr

      - name: Get release asset URL
        id: getReleaseUrl
        run: |
          TAG="${{ github.event.release.tag_name }}"
          REPO="${{ github.repository }}"

          ASSET_INFO=$(curl -s "https://api.github.com/repos/${REPO}/releases/tags/${TAG}")
              
          echo "$ASSET_INFO" | jq -r '.assets[] | "\(.name)=\(.browser_download_url)"' > assets.txt

          cat assets.txt

          echo "ASSET_LIST=$(cat assets.txt | jq -Rs .)" >> "$GITHUB_OUTPUT"

      - name: Download all release assets
        run: |
          while IFS='=' read -r name url; do
            echo "Downloading $name"
            curl -L -o "$name" "$url"
          done < assets.txt

      - name: Submit to CRAN using devtools
        run: |
          cli::cli_inform("Using devtools for submission. Rebuilding the package...")

          # Override the 'devtools::yesno' function to always behave as if "yes" was selected
          unlockBinding("yesno", asNamespace("devtools"))
          assign("yesno", function(...) FALSE, envir = asNamespace("devtools"))
          lockBinding("yesno", asNamespace("devtools"))

          devtools::submit_cran() # Rebuilds the package
        shell: Rscript {0}
