name: Update NEWS.md

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      NEW_VERSION:
        required: true
        type: string

    secrets:
      ARTMA_BOT_COMMIT_TOKEN:
        description: ArtmaBot personal access token, used to workaround committing to protected branch
        required: true


jobs:
  validateActor:
    runs-on: ubuntu-latest
    outputs:
      HAS_WRITE_ACCESS: ${{ contains(fromJSON('["write", "admin"]'), steps.getUserPermissions.outputs.PERMISSION) }}
    steps:
      - name: Get user permissions
        id: getUserPermissions
        run: echo "PERMISSION=$(gh api /repos/${{ github.repository }}/collaborators/${{ github.actor }}/permission | jq -r '.permission')" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.ARTMA_BOT_COMMIT_TOKEN }}

  updateNews:
    runs-on: macos-latest
    needs: validateActor
    if: ${{ fromJSON(needs.validateActor.outputs.HAS_WRITE_ACCESS) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.ARTMA_BOT_COMMIT_TOKEN }}

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install git-chglog
        run: |
          brew tap git-chglog/git-chglog
          brew install git-chglog

      - name: Setup git for ArtmaBot
        uses: ./.github/actions/composite/setupGitForArtmaBot
        id: setupGitForArtmaBot
        with:
          GPG_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Update NEWS
        run: |
          git-chglog --output NEWS.md --next-tag "v${{ inputs.NEW_VERSION }}"

      - name: Commit NEWS if changed
        run: |
          git add NEWS.md
          if ! git diff --cached --quiet; then
            git commit -m "chore: update NEWS"
            git push
          else
            echo "No changes to NEWS.md"
          fi

      - name: Push changes to master
        run: |
          git remote set-url origin git@github.com:${{ github.repository }}.git
          git pull --rebase origin master
          git push origin master

      - name: Upload NEWS.md
        uses: actions/upload-artifact@v4
        with:
          name: NEWS.md
          path: NEWS.md
